# GitHub Actionsを使ってDiscordでリマインドを行う方法
# このスクリプトは、GitHub Actionsを使って毎週火曜日の13:00にDiscordのWebhookを使ってリマインドを送信します。

name: Weekly Discord Reminder

on:
  push:
    branches:
      - main  # mainブランチにプッシュしたときに実行します
  schedule:
    - cron: '0 4 * * 2'  # 毎週火曜日の13:00 (UTCは4:00に相当)

jobs:
  send_reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Reminder
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby
        echo "require 'net/http'; require 'uri'; require 'json';
              WEBHOOK_URL = ENV['WEBHOOK_URL'];
              REMINDER_MESSAGE = '@冬プロジェクト 今日は進捗報告デーです！ チームの進捗と今週の目標を確認し，進捗確認フォーラムへ投稿しましょう！';
              def send_reminder
                uri = URI.parse(WEBHOOK_URL)
                header = { 'Content-Type' => 'application/json' }
                payload = { content: REMINDER_MESSAGE }.to_json
                http = Net::HTTP.new(uri.host, uri.port)
                http.use_ssl = true
                request = Net::HTTP::Post.new(uri.request_uri, header)
                request.body = payload
                response = http.request(request)
                puts "Response \#{response.code} \#{response.message}: \#{response.body}"
              end
              send_reminder" > reminder_script.rb
        ruby reminder_script.rb
